# Generated by Django 5.0.3 on 2026-07-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
