# Generated by Django 5.0.3 on 2026-07-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
