# Generated by Django 5.0.3 on 2026-07-10 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supplier_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('realizado_por', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_resultante', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.product')),
            ],
        ),
    ]
