# Generated by Django 5.0.3 on 2026-07-28 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_maintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='furniture_products/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.furniturecategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.furnituredepartment')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.media')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.furnituresupplier')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('realizado_por', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_resultante', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.furnitureproduct')),
            ],
        ),
    ]
