# Generated by Django 5.0.3 on 2026-07-28 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_furniturecategory_furnituredepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('estado_actual', models.CharField(choices=[('En Sindicato', 'En Sindicato'), ('Fuera del Sindicato', 'Fuera del Sindicato')], default='En Sindicato', max_length=50)),
                ('foto_vehiculo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_viaje', models.CharField(choices=[('En Curso', 'En Curso'), ('Finalizado', 'Finalizado')], default='En Curso', max_length=20)),
                ('descripcion_salida', models.TextField()),
                ('fecha_hora_salida', models.DateTimeField(auto_now_add=True)),
                ('kilometraje_salida', models.IntegerField()),
                ('gasolina_salida', models.IntegerField(help_text='Porcentaje de gasolina (0-100)')),
                ('foto_evidencia_salida', models.ImageField(upload_to='vehicle_trips/salidas/')),
                ('fecha_hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('kilometraje_llegada', models.IntegerField(blank=True, null=True)),
                ('gasolina_llegada', models.IntegerField(blank=True, help_text='Porcentaje de gasolina (0-100)', null=True)),
                ('foto_evidencia_llegada', models.ImageField(blank=True, null=True, upload_to='vehicle_trips/llegadas/')),
                ('descripcion_llegada', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.vehicle')),
            ],
        ),
    ]
