# Generated by Django 5.0.3 on 2026-08-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vehicle_vehicletrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Sindicato de Choferes Profesionales del Cantón Espejo', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('primary_color', models.CharField(default='#148143', max_length=20)),
            ],
        ),
    ]
