# Generated by Django 5.2.5 on 2026-08-04 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletrip',
            old_name='descripcion_llegada',
            new_name='novedades_observaciones',
        ),
        migrations.RemoveField(
            model_name='vehicletrip',
            name='gasolina_llegada',
        ),
        migrations.RemoveField(
            model_name='vehicletrip',
            name='gasolina_salida',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='precio_diesel',
            field=models.DecimalField(decimal_places=2, default=1.75, max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='precio_gasolina',
            field=models.DecimalField(decimal_places=2, default=2.4, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacidad_tanque_galones',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='combustible_actual_galones',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fecha_vencimiento_matricula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mes_matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometro_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rendimiento_km_por_galon',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tipo_combustible',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel')], default='Gasolina', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicletrip',
            name='costo_combustible_viaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletrip',
            name='galones_recargados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicletrip',
            name='km_recorridos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletrip',
            name='descripcion_salida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=50)),
                ('tipo_licencia', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('En Viaje', 'En Viaje'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=200)),
                ('fecha_ultimo_cambio', models.DateField()),
                ('km_ultimo_cambio', models.IntegerField()),
                ('frecuencia_km', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.vehicle')),
            ],
        ),
    ]
