# Generated by Django 5.0.3 on 2026-08-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_descripcion_llegada_vehicletrip_novedades_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='conductores/'),
        ),
    ]
