# Generated by Django 5.0.3 on 2026-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_driverprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
