# Generated by Django 5.2.5 on 2026-08-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_driverprofile_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('taller', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('factura_foto', models.ImageField(blank=True, null=True, upload_to='vehicles/maintenances/facturas/')),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='api.vehiclemaintenance')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='api.vehicle')),
            ],
        ),
    ]
