# Generated by Django 5.0.3 on 2026-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_vehicle_chasis_vehicle_clase_vehicle_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='fecha_emision_licencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
