# Generated by Django 5.0.3 on 2026-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_driverprofile_fecha_emision_licencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='fecha_proximo_cambio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
