# Generated by Django 5.0.3 on 2026-08-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_vehiclemaintenance_fecha_proximo_cambio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('año_matriculado', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lugar_tramite', models.CharField(blank=True, max_length=200, null=True)),
                ('nueva_fecha_vencimiento', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.vehicle')),
            ],
        ),
    ]
