# Generated by Django 5.0.3 on 2026-08-07 16:10
# Modified to fix duplicate public_id values before adding unique constraint

import uuid
from django.db import migrations, models


def populate_unique_public_ids(apps, schema_editor):
    """
    Ensure every row in each model has a unique, non-null public_id
    before the unique constraint is applied.
    """
    model_names = [
        'Category',
        'Department',
        'DriverProfile',
        'FurnitureCategory',
        'FurnitureDepartment',
        'FurnitureProduct',
        'FurnitureSupplier',
        'Product',
        'Supplier',
        'Vehicle',
    ]
    for model_name in model_names:
        try:
            Model = apps.get_model('api', model_name)
        except LookupError:
            continue
        # Assign a fresh UUID to every row to guarantee uniqueness
        for obj in Model.objects.all():
            obj.public_id = uuid.uuid4()
            obj.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_category_public_id_department_public_id_and_more'),
    ]

    operations = [
        # Step 1: Populate unique UUIDs for all existing rows
        migrations.RunPython(
            populate_unique_public_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 2: Now safely apply the unique constraint
        migrations.AlterField(
            model_name='category',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='furniturecategory',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='furnituredepartment',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='furnitureproduct',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='furnituresupplier',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
