# Generated by Django 5.2.5 on 2026-08-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_seed_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='licencias',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
