# Generated by Django 5.2.5 on 2026-08-21 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_driverprofile_licencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='fallo_observado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='solucion_aplicada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='Preventivo', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancerecord',
            name='fallo_observado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancerecord',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancerecord',
            name='solucion_aplicada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancerecord',
            name='subtotal_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancerecord',
            name='subtotal_materiales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancerecord',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_maintenance_records', to='api.supplier'),
        ),
        migrations.AddField(
            model_name='vehiclemaintenancerecord',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='Preventivo', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicleregistrationrecord',
            name='documento_pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/matriculas/'),
        ),
        migrations.AddField(
            model_name='vehicleregistrationrecord',
            name='documento_pdf_2',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/matriculas/'),
        ),
        migrations.AddField(
            model_name='vehicleregistrationrecord',
            name='documento_pdf_3',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/matriculas/'),
        ),
        migrations.AddField(
            model_name='vehicleregistrationrecord',
            name='observaciones_pendientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='frecuencia_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='km_ultimo_cambio',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VehicleFuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vale', models.DateField()),
                ('numero_vale', models.CharField(max_length=50)),
                ('galones', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('odometro_recarga', models.IntegerField()),
                ('motivo', models.CharField(choices=[('Comisiones', 'Comisiones'), ('Prácticas de conducción', 'Prácticas de conducción'), ('Operación normal', 'Operación normal'), ('Otro', 'Otro')], default='Comisiones', max_length=50)),
                ('motivo_detalle', models.TextField(blank=True, null=True)),
                ('tipo_combustible', models.CharField(default='Gasolina Extra', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='api.vehicle')),
            ],
        ),
    ]
