# Generated by Django 5.2.5 on 2026-08-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_vehiclesupplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclefuellog',
            old_name='motivo_detalle',
            new_name='concepto',
        ),
        migrations.RemoveField(
            model_name='vehiclefuellog',
            name='motivo',
        ),
        migrations.AddField(
            model_name='vehiclefuellog',
            name='precio_por_galon',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehiclefuellog',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclefuellog',
            name='supervisado_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclefuellog',
            name='tipo_transaccion',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('PREPAGO', 'Prepago'), ('CONSUMO INTERNO', 'Consumo Interno'), ('CALIBRACION', 'Calibración'), ('DECRETO', 'Decreto'), ('DINERO ELECTRONICO', 'Dinero Electrónico'), ('MIDENA', 'Midena')], default='EFECTIVO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclefuellog',
            name='galones',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='vehiclefuellog',
            name='tipo_combustible',
            field=models.CharField(choices=[('EXTRA', 'Gasolina Extra'), ('SUPER', 'Gasolina Súper'), ('DIESEL', 'Diésel')], default='EXTRA', max_length=20),
        ),
    ]
