# Generated by Django 5.2.5 on 2026-08-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_motivo_detalle_vehiclefuellog_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tipo_combustible',
            field=models.CharField(choices=[('Gasolina Extra', 'Gasolina Extra'), ('Diesel', 'Diesel')], default='Gasolina', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclefuellog',
            name='tipo_combustible',
            field=models.CharField(choices=[('EXTRA', 'Gasolina Extra'), ('DIESEL', 'Diésel')], default='EXTRA', max_length=20),
        ),
    ]
