# Generated by Django 5.2.5 on 2026-08-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_vehicle_tipo_combustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclefuellog',
            name='foto_vale',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/fuel_vouchers/', verbose_name='Fotografía del Vale'),
        ),
    ]
