# Generated by Django 5.2.5 on 2026-08-24 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_vehiclefuellog_foto_vale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_total', models.DecimalField(decimal_places=2, default=1500.0, max_digits=12)),
                ('saldo_gasolina', models.DecimalField(decimal_places=2, default=300.0, max_digits=12)),
                ('saldo_diesel', models.DecimalField(decimal_places=2, default=1200.0, max_digits=12)),
                ('limite_alerta', models.DecimalField(decimal_places=2, default=40.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='estado_correctivo',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Ejecutado', 'Ejecutado')], default='Pendiente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='factura_foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/maintenances/facturas/'),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='kilometraje_falla',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='subtipo_correctivo',
            field=models.CharField(blank=True, choices=[('Urgente', 'Urgente'), ('Programado', 'Programado')], default='Programado', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicletrip',
            name='ruta_practica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicletrip',
            name='tipo_motivo',
            field=models.CharField(choices=[('Prácticas', 'Prácticas'), ('Comisión', 'Comisión'), ('Guincha', 'Guincha'), ('Otro', 'Otro')], default='Prácticas', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tipo_combustible',
            field=models.CharField(choices=[('Gasolina Extra', 'Gasolina Extra'), ('Diesel', 'Diesel')], default='Gasolina Extra', max_length=20),
        ),
        migrations.CreateModel(
            name='DriverVehicleHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acta', models.CharField(choices=[('Entrega', 'Entrega'), ('Recepción', 'Recepción')], default='Entrega', max_length=20)),
                ('fecha', models.DateField()),
                ('kilometraje', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documento_acta_firmada', models.FileField(blank=True, null=True, upload_to='vehicles/handovers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_records', to='api.vehicle')),
            ],
        ),
    ]
