# Generated by Django 5.2.5 on 2026-08-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_fuelbudget_vehiclemaintenance_estado_correctivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelbudget',
            name='base_diesel',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fuelbudget',
            name='base_gasolina',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=12),
        ),
    ]
