# Generated by Django 5.2.5 on 2026-09-10 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_fuelbudget_base_diesel_fuelbudget_base_gasolina'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTemplate',
            fields=[
                ('puntuacion', models.IntegerField(primary_key=True, serialize=False)),
                ('observacion_predeterminada', models.TextField()),
                ('recomendacion_predeterminada', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_semanas', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_minima_aprobacion', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='InstructorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_licencia', models.CharField(default='C', max_length=50)),
                ('circuito_ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_as_instructor', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_as_student', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.vehicle')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PhaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ejemplo_practico', models.TextField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.learningphase')),
            ],
            options={
                'ordering': ['phase__numero', 'numero'],
                'unique_together': {('phase', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyInstructorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('periodo_academico', models.CharField(default='2025-2026', max_length=100)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('REVISADO', 'Revisado por Inspector'), ('APROBADO', 'Aprobado por Dirección')], default='BORRADOR', max_length=30)),
                ('elaborado_por_nombre', models.CharField(max_length=255)),
                ('revisado_por_nombre', models.CharField(default='Javier Godoy - INSPECTOR GENERAL', max_length=255)),
                ('aprobado_por_nombre', models.CharField(default='Germania Paguay - DIRECTOR PEDAGÓGICO', max_length=255)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PracticalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente 🟩'), ('RETRASO', 'Retraso 🟨'), ('AUSENTE', 'Ausente 🟥')], default='PRESENTE', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('student', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.phaseactivity')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_instructor', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity__phase__numero', 'activity__numero'],
                'unique_together': {('student', 'activity')},
            },
        ),
    ]
