# Generated by Django 5.2.5 on 2026-09-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_student_alter_instructorschedule_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentevaluation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='vehiculo_rotacion',
            field=models.CharField(choices=[('ESTANDAR', 'Estándar'), ('NPR', 'Camión NPR'), ('SINOTRUC_BLANCO', 'Sinotruc Blanco (Uñeta)'), ('SINOTRUC_GRIS', 'Sinotruc Gris (Palanca)'), ('TRAILER', 'Tráiler / Bus')], default='ESTANDAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='tipo_licencia',
            field=models.CharField(choices=[('C', 'Licencia Tipo C'), ('D_REGULAR', 'Licencia Tipo D (Regular)'), ('D_CONVALIDADA', 'Licencia Tipo D (Convalidada)'), ('E_REGULAR', 'Licencia Tipo E (Regular)'), ('E_CONVALIDADA', 'Licencia Tipo E (Convalidada)')], default='C', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='studentevaluation',
            unique_together={('student', 'activity', 'vehiculo_rotacion')},
        ),
    ]
