# Generated by Django 5.2.5 on 2026-09-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_student_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='assigned_vehicles',
            field=models.ManyToManyField(blank=True, related_name='responsible_instructors', to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='licencias_habilitadas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
