# Generated by Django 5.2.5 on 2026-09-19 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_instructorprofile_assigned_vehicles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DEBERES', 'Deberes'), ('TRABAJO_GRUPO', 'Trabajo en Grupo'), ('PRUEBA', 'Prueba'), ('EXAMEN', 'Examen'), ('ROTACION_VEHICULO', 'Rotación Vehicular')], max_length=50)),
                ('nombre_evaluacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('vehiculo_rotacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_evaluations', to='api.student')),
            ],
            options={
                'ordering': ['student', 'categoria', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='ClassSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tema_actividad', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_classes', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_logs', to='api.instructorschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_logs', to='api.student')),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
